import numpy as np

# Constants

G = 6.67430e-11
AU = 1.496e11

# Masses

SUN_MASS = 1.989e30
MERCURY_MASS = 3.301e23
VENUS_MASS = 4.867e24
EARTH_MASS = 5.972e24
MARS_MASS = 6.417e23
JUPITER_MASS = 1.898e27
SATURN_MASS = 5.683e26
URANUS_MASS = 8.681e25
NEPTUNE_MASS = 1.024e26

# Orbital Parameters

MERCURY_SEMI_MAJOR_AXIS = 0.387 * AU
VENUS_SEMI_MAJOR_AXIS = 0.723 * AU
EARTH_SEMI_MAJOR_AXIS = 1.000 * AU
MARS_SEMI_MAJOR_AXIS = 1.524 * AU
JUPITER_SEMI_MAJOR_AXIS = 5.203 * AU
SATURN_SEMI_MAJOR_AXIS = 9.537 * AU
URANUS_SEMI_MAJOR_AXIS = 19.191 * AU
NEPTUNE_SEMI_MAJOR_AXIS = 30.070 * AU

MERCURY_ECCENTRICITY = 0.2056
VENUS_ECCENTRICITY = 0.0068
EARTH_ECCENTRICITY = 0.0167
MARS_ECCENTRICITY = 0.0934
JUPITER_ECCENTRICITY = 0.0489
SATURN_ECCENTRICITY = 0.0565
URANUS_ECCENTRICITY = 0.0472
NEPTUNE_ECCENTRICITY = 0.0086

# Perihelion Distances

MERCURY_PERIHELION_DISTANCE = MERCURY_SEMI_MAJOR_AXIS * (1 - MERCURY_ECCENTRICITY)
VENUS_PERIHELION_DISTANCE = VENUS_SEMI_MAJOR_AXIS * (1 - VENUS_ECCENTRICITY)
EARTH_PERIHELION_DISTANCE = EARTH_SEMI_MAJOR_AXIS * (1 - EARTH_ECCENTRICITY)
MARS_PERIHELION_DISTANCE = MARS_SEMI_MAJOR_AXIS * (1 - MARS_ECCENTRICITY)
JUPITER_PERIHELION_DISTANCE = JUPITER_SEMI_MAJOR_AXIS * (1 - JUPITER_ECCENTRICITY)
SATURN_PERIHELION_DISTANCE = SATURN_SEMI_MAJOR_AXIS * (1 - SATURN_ECCENTRICITY)
URANUS_PERIHELION_DISTANCE = URANUS_SEMI_MAJOR_AXIS * (1 - URANUS_ECCENTRICITY)
NEPTUNE_PERIHELION_DISTANCE = NEPTUNE_SEMI_MAJOR_AXIS * (1 - NEPTUNE_ECCENTRICITY)

# Initial Positions

SUN_POSITION = np.array([0.0, 0.0, 0.0])

MERCURY_INITIAL_POSITION = np.array([MERCURY_PERIHELION_DISTANCE, 0.0, 0.0])
VENUS_INITIAL_POSITION = np.array([VENUS_PERIHELION_DISTANCE, 0.0, 0.0])
EARTH_INITIAL_POSITION = np.array([EARTH_PERIHELION_DISTANCE, 0.0, 0.0])
MARS_INITIAL_POSITION = np.array([MARS_PERIHELION_DISTANCE, 0.0, 0.0])
JUPITER_INITIAL_POSITION = np.array([JUPITER_PERIHELION_DISTANCE, 0.0, 0.0])
SATURN_INITIAL_POSITION = np.array([SATURN_PERIHELION_DISTANCE, 0.0, 0.0])
URANUS_INITIAL_POSITION = np.array([URANUS_PERIHELION_DISTANCE, 0.0, 0.0])
NEPTUNE_INITIAL_POSITION = np.array([NEPTUNE_PERIHELION_DISTANCE, 0.0, 0.0])

# Initial Orbital Speeds

MERCURY_INITIAL_ORBITAL_SPEED = np.sqrt(G * SUN_MASS * (2 / MERCURY_PERIHELION_DISTANCE - 1 / MERCURY_SEMI_MAJOR_AXIS))
VENUS_INITIAL_ORBITAL_SPEED = np.sqrt(G * SUN_MASS * (2 / VENUS_PERIHELION_DISTANCE - 1 / VENUS_SEMI_MAJOR_AXIS))
EARTH_INITIAL_ORBITAL_SPEED = np.sqrt(G * SUN_MASS * (2 / EARTH_PERIHELION_DISTANCE - 1 / EARTH_SEMI_MAJOR_AXIS))
MARS_INITIAL_ORBITAL_SPEED = np.sqrt(G * SUN_MASS * (2 / MARS_PERIHELION_DISTANCE - 1 / MARS_SEMI_MAJOR_AXIS))
JUPITER_INITIAL_ORBITAL_SPEED = np.sqrt(G * SUN_MASS * (2 / JUPITER_PERIHELION_DISTANCE - 1 / JUPITER_SEMI_MAJOR_AXIS))
SATURN_INITIAL_ORBITAL_SPEED = np.sqrt(G * SUN_MASS * (2 / SATURN_PERIHELION_DISTANCE - 1 / SATURN_SEMI_MAJOR_AXIS))
URANUS_INITIAL_ORBITAL_SPEED = np.sqrt(G * SUN_MASS * (2 / URANUS_PERIHELION_DISTANCE - 1 / URANUS_SEMI_MAJOR_AXIS))
NEPTUNE_INITIAL_ORBITAL_SPEED = np.sqrt(G * SUN_MASS * (2 / NEPTUNE_PERIHELION_DISTANCE - 1 / NEPTUNE_SEMI_MAJOR_AXIS))

# Initial Velocities

MERCURY_INITIAL_VELOCITY = np.array([0.0, MERCURY_INITIAL_ORBITAL_SPEED, 0.0])
VENUS_INITIAL_VELOCITY = np.array([0.0, VENUS_INITIAL_ORBITAL_SPEED, 0.0])
EARTH_INITIAL_VELOCITY = np.array([0.0, EARTH_INITIAL_ORBITAL_SPEED, 0.0])
MARS_INITIAL_VELOCITY = np.array([0.0, MARS_INITIAL_ORBITAL_SPEED, 0.0])
JUPITER_INITIAL_VELOCITY = np.array([0.0, JUPITER_INITIAL_ORBITAL_SPEED, 0.0])
SATURN_INITIAL_VELOCITY = np.array([0.0, SATURN_INITIAL_ORBITAL_SPEED, 0.0])
URANUS_INITIAL_VELOCITY = np.array([0.0, URANUS_INITIAL_ORBITAL_SPEED, 0.0])
NEPTUNE_INITIAL_VELOCITY = np.array([0.0, NEPTUNE_INITIAL_ORBITAL_SPEED, 0.0])

# Sun Initial Velocity (Using COM)

PLANET_MASSES = np.array([MERCURY_MASS, VENUS_MASS, EARTH_MASS, MARS_MASS, JUPITER_MASS, SATURN_MASS, URANUS_MASS, NEPTUNE_MASS])

PLANET_VELOCITIES = np.array([MERCURY_INITIAL_VELOCITY, VENUS_INITIAL_VELOCITY, EARTH_INITIAL_VELOCITY, MARS_INITIAL_VELOCITY, JUPITER_INITIAL_VELOCITY, SATURN_INITIAL_VELOCITY, URANUS_INITIAL_VELOCITY, NEPTUNE_INITIAL_VELOCITY])

SUN_INITIAL_VELOCITY = -np.sum(PLANET_MASSES[:, np.newaxis] * PLANET_VELOCITIES, axis=0) / SUN_MASS