import numpy as np

# Constants

G = 6.67430e-11
AU = 1.496e11

SUN_MASS = 1.989e30
EARTH_MASS = 5.972e24

# Earth Orbital Parameters

EARTH_ECCENTRICITY = 0.0167
EARTH_SEMI_MAJOR_AXIS = AU

EARTH_PERIHELION_DISTANCE = EARTH_SEMI_MAJOR_AXIS * (1 - EARTH_ECCENTRICITY)
EARTH_APHELION_DISTANCE = EARTH_SEMI_MAJOR_AXIS * (1 + EARTH_ECCENTRICITY)

# Initial Positions

SUN_POSITION = np.array([0.0, 0.0])
EARTH_INITIAL_POSITION = np.array([EARTH_PERIHELION_DISTANCE, 0.0])

# Initial Velocity

EARTH_INITIAL_ORBITAL_SPEED = np.sqrt(G * SUN_MASS * (2 / EARTH_PERIHELION_DISTANCE - 1 / EARTH_SEMI_MAJOR_AXIS))
EARTH_INITIAL_VELOCITY = np.array([0.0, EARTH_INITIAL_ORBITAL_SPEED])
SUN_INITIAL_VELOCITY = -(EARTH_MASS / SUN_MASS) * EARTH_INITIAL_VELOCITY